// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcQeEVS8NsBblmFlnWxQrvO7RJEB7yMUI',
    appId: '1:157988111065:web:afb9cc4a282a194602f4c8',
    messagingSenderId: '157988111065',
    projectId: 'hashplusapp-75bf8',
    authDomain: 'hashplusapp-75bf8.firebaseapp.com',
    storageBucket: 'hashplusapp-75bf8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsHxSTWyBXG4phPQ7SIIdtZVtJzKavO5Q',
    appId: '1:157988111065:android:55a44f40b7e87c2c02f4c8',
    messagingSenderId: '157988111065',
    projectId: 'hashplusapp-75bf8',
    storageBucket: 'hashplusapp-75bf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVIubhfljoUHxEi9BjJdSGnJzWuCWW7Zs',
    appId: '1:157988111065:ios:44468e5d2191cc0402f4c8',
    messagingSenderId: '157988111065',
    projectId: 'hashplusapp-75bf8',
    storageBucket: 'hashplusapp-75bf8.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVIubhfljoUHxEi9BjJdSGnJzWuCWW7Zs',
    appId: '1:157988111065:ios:44468e5d2191cc0402f4c8',
    messagingSenderId: '157988111065',
    projectId: 'hashplusapp-75bf8',
    storageBucket: 'hashplusapp-75bf8.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcQeEVS8NsBblmFlnWxQrvO7RJEB7yMUI',
    appId: '1:157988111065:web:71e53c7443ffecb702f4c8',
    messagingSenderId: '157988111065',
    projectId: 'hashplusapp-75bf8',
    authDomain: 'hashplusapp-75bf8.firebaseapp.com',
    storageBucket: 'hashplusapp-75bf8.firebasestorage.app',
  );
}
